name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Remove Negative Sentiment & Angry or Sad Emotion Word Cloud.png
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch 'Negative Sentiment & Angry or Sad Emotion Word Cloud.png'" --prune-empty --tag-name-filter cat -- --all

      - name: Remove Overall Word Cloud.png
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch 'Overall Word Cloud.png'" --prune-empty --tag-name-filter cat -- --all

      - name: Remove Positive Sentiment & Happy Emotion Word Cloud.png
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch 'Positive Sentiment & Happy Emotion Word Cloud.png'" --prune-empty --tag-name-filter cat -- --all
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://dhanikitkat:$HF_TOKEN@huggingface.co/spaces/dhanikitkat/sentiment_emotion main
